name: Build and Test
on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'develop' && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  number: ${{ github.event.pull_request.number || -1 }}
  head_sha: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
  head_branch: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
  base_sha: ${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}
  base_branch: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}
  base_owner: ${{ github.event.pull_request.base.repo.owner.login || github.repository_owner }}
  is_fork: ${{ github.event.pull_request.head.repo.fork || false }}
  ref: ${{ github.sha }}

jobs:
  determine-affected:
    uses: ./.github/workflows/affected-reusable.yml

  test-libraries:
    name: "Test Libraries"
    needs: determine-affected
    runs-on: ubuntu-22.04
    if: ${{contains(join(needs.determine-affected.outputs.paths,','), 'libs')}}
    env:
      PATHS: ${{ needs.determine-affected.outputs.paths }}
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Lib found!"
